/* --- This file was auto-generated by scripts/prebuild.js --- */

export const environment = {
  CLIENT_ID: '0oa2ol5yktBxSSdxJ0g7',
  REDIRECT_URI: 'http://localhost:3000/implicit/callback',
  ISSUER: 'https://sdk-test.trexcloud.com/oauth2/default',
  USERNAME: 'aaron.granick@okta.com',
  PASSWORD: 'Abcd1234',
  OKTA_TESTING_DISABLEHTTPSCHECK: false,
  BASE_URI: 'http://localhost:3000',
  PORT: 3000,
  production: false
};
